# News2Stock Analyser 데이터 준비
뉴스 기사를 전달하면 긍/부정 분석 뿐 아니라 특정 주식에 대한 긍/부정 평가를 하는 모델 구현

In [3]:
from dotenv import load_dotenv

load_dotenv()

True

## 데이터 준비
https://huggingface.co/datasets/daekeun-ml/naver-news-summarization-ko

In [ ]:
# %pip install datasets openai

Collecting datasets
  Downloading datasets-4.8.5-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: openai in c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages (2.34.0)
Requirement already satisfied: filelock in c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages (from datasets) (3.29.0)
Requirement already satisfied: numpy>=1.17 in c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages (from datasets) (2.4.4)
Requirement already satisfied: pyarrow>=21.0.0 in c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages (from datasets) (24.0.0)
Collecting dill<0.4.2,>=0.3.0 (from datasets)
  Downloading dill-0.4.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages (from datasets) (3.0.2)
Requirement already satisfied: requests>=2.32.2 in c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages (from datasets) (2.33.1)
Requirement already satisfied: httpx<1.0.0 in c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages (from datasets) (3.7.0)
Collecting multiprocess<0.70.20 (from datasets)
  Downloading multiprocess-0.70.19-py312-none-any.whl.metadata (7.5 kB)
Collecting fsspec<=2026.2.0,>=2023.1.0 (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading fsspec-2026.2.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages (from datasets) (1.12.0)
Requirement already satisfied: packaging in c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages (from datasets) (24.2)
Requirement already satisfied: pyyaml>=5.1 in c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.13.5)
Requirement already satisfied: anyio in c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages (from httpx<1.0.0->datasets) (4.13.0)
Requirement already satisfied: certifi in c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages (from httpx<1.0.0->datasets) (2026.4.22)
Requirement already satisfied: httpcore==1.* in c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages (from httpx<1.0.0->datasets) (3.13)
Requirement already satisfied: h11>=0.16 in c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.4.3)
Requirement already satisfied: typer in c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (0.25.0)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.15.0)
Requirement already satisfied: distro<2,>=1.7.0 in c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages (from openai) (1.9.0)
Requirement already satisfied: jiter<1,>=0.10.0 in c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages (from openai) (0.14.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages (from openai) (2.12.5)
Requirement already satisfied: sniffio in c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages (from openai) (1.3.1)
Requirement already satisfied: annotated-types>=0.6.0 in c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages (from pydantic<3,>=1.9.0->openai) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages (from pydantic<3,>=1.9.0->openai) (0.4.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages (from requests>=2.32.2->datasets) (2.6.3)
Requirement already satisfied: colorama in c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages (from tqdm>=4.66.3->datasets) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages (from pandas->datasets) (2026.2)
Requirement already satisfied: six>=1.5 in c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: click>=8.2.1 in c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages (from rich>=13.8.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages (from rich>=13.8.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (0.1.2)
Downloading datasets-4.8.5-py3-none-any.whl (528 kB)
   ---------------------------------------- 0.0/529.0 kB ? eta -:--:--
   ---------------------------------------- 529.0/529.0 kB 17.8 MB/s  0:00:00
Downloading dill-0.4.1-py3-none-any.whl (120 kB)
Downloading fsspec-2026.2.0-py3-none-any.whl (202 kB)
Downloading multiprocess-0.70.19-py312-none-any.whl (150 kB)
Installing collected packages: fsspec, dill, multiprocess, datasets

  Attempting uninstall: fsspec

    Found existing installation: fsspec 2026.3.0

    Uninstalling fsspec-2026.3.0:

      Successfully uninstalled fsspec-2026.3.0

   ---------------------------------------- 0/4 [fsspec]
   ---------- ----------------------------- 1/4 [dill]
   -------------------- ------------------- 2/4 [multiprocess]
   -------------------- ------------------- 2/4 [multiprocess]
   ------------------------------ --------- 3/4 [datasets]
   ------------------------------ --------- 3/4 [datasets]
   ------------------------------ --------- 3/4 [datasets]
   ------------------------------ --------- 3/4 [datasets]
   ---------------------------------------- 4/4 [datasets]

Successfully installed datasets-4.8.5 dill-0.4.1 fsspec-2026.2.0 multiprocess-0.70.19
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
from datasets import load_dataset

dataset = load_dataset('daekeun-ml/naver-news-summarization-ko')

README.md:   0%|          | 0.00/787 [00:00<?, ?B/s]

c:\Users\Playdata\AppData\Local\miniforge3\envs\dl_nlp_env\Lib\site-packages\huggingface_hub\file_download.py:138: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Playdata\.cache\huggingface\hub\datasets--daekeun-ml--naver-news-summarization-ko. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

train.csv:   0%|          | 0.00/66.3M [00:00<?, ?B/s]

validation.csv: 0.00B [00:00, ?B/s]

test.csv: 0.00B [00:00, ?B/s]

Generating train split:   0%|          | 0/22194 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/2466 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/2740 [00:00<?, ? examples/s]

In [4]:
dataset

DatasetDict({
    train: Dataset({
        features: ['date', 'category', 'press', 'title', 'document', 'link', 'summary'],
        num_rows: 22194
    })
    validation: Dataset({
        features: ['date', 'category', 'press', 'title', 'document', 'link', 'summary'],
        num_rows: 2466
    })
    test: Dataset({
        features: ['date', 'category', 'press', 'title', 'document', 'link', 'summary'],
        num_rows: 2740
    })
})

In [5]:
# train dataset에서 economy 뉴스만 필터링
economy_dataset = dataset['train'].filter(lambda row:row['category']=='economy')
print(len(economy_dataset))
economy_dataset[0]

Filter:   0%|          | 0/22194 [00:00<?, ? examples/s]

17088

{'date': '2022-07-03 17:14:37',
 'category': 'economy',
 'press': 'YTN ',
 'title': '추경호 중기 수출지원 총력 무역금융 40조 확대',
 'document': '앵커 정부가 올해 하반기 우리 경제의 버팀목인 수출 확대를 위해 총력을 기울이기로 했습니다. 특히 수출 중소기업의 물류난 해소를 위해 무역금융 규모를 40조 원 이상 확대하고 물류비 지원과 임시선박 투입 등을 추진하기로 했습니다. 류환홍 기자가 보도합니다. 기자 수출은 최고의 실적을 보였지만 수입액이 급증하면서 올해 상반기 우리나라 무역수지는 역대 최악인 103억 달러 적자를 기록했습니다. 정부가 수출확대에 총력을 기울이기로 한 것은 원자재 가격 상승 등 대외 리스크가 가중되는 상황에서 수출 증가세 지속이야말로 한국경제의 회복을 위한 열쇠라고 본 것입니다. 추경호 경제부총리 겸 기획재정부 장관 정부는 우리 경제의 성장엔진인 수출이 높은 증가세를 지속할 수 있도록 총력을 다하겠습니다. 우선 물류 부담 증가 원자재 가격 상승 등 가중되고 있는 대외 리스크에 대해 적극 대응하겠습니다. 특히 중소기업과 중견기업 수출 지원을 위해 무역금융 규모를 연초 목표보다 40조 원 늘린 301조 원까지 확대하고 물류비 부담을 줄이기 위한 대책도 마련했습니다. 이창양 산업통상자원부 장관 국제 해상운임이 안정될 때까지 월 4척 이상의 임시선박을 지속 투입하는 한편 중소기업 전용 선복 적재 용량 도 현재보다 주당 50TEU 늘려 공급하겠습니다. 하반기에 우리 기업들의 수출 기회를 늘리기 위해 2 500여 개 수출기업을 대상으로 해외 전시회 참가를 지원하는 등 마케팅 지원도 벌이기로 했습니다. 정부는 또 이달 중으로 반도체를 비롯한 첨단 산업 육성 전략을 마련해 수출 증가세를 뒷받침하고 에너지 소비를 줄이기 위한 효율화 방안을 마련해 무역수지 개선에 나서기로 했습니다. YTN 류환홍입니다.',
 'link': 'https://n.news.naver.com/mnews/article/052/0001759333?sid=101',
 'summary': '올해 상반기 우리나라 무역수지는 역대 최악인 103억 달러 적자를 기록한 가운데, 정부가 하반기에 우리 경제의 버팀목인 수출 확대를 위해 총력을 기울이기로 결정한 가운데, 특히 수출 중소기업의 물류난 해소를 위해 무역금융 규모를 40조 원 이상 확대하고 물류비 지원과 임시선박 투입 등을 추진하기로 했다.'}

In [9]:
# DataFrame 변환
df = economy_dataset.to_pandas()
df.head()

,date,category,press,title,document,link,summary
0,2022-07-03 17:14:37,economy,YTN,추경호 중기 수출지원 총력 무역금융 40조 확대,앵커 정부가 올해 하반기 우리 경제의 버팀목인 수출 확대를 위해 총력을 기울이기로 ...,https://n.news.naver.com/mnews/article/052/000...,"올해 상반기 우리나라 무역수지는 역대 최악인 103억 달러 적자를 기록한 가운데, ..."
1,2022-07-04 08:07:12,economy,아시아경제,해산물·주류 무제한 인터컨티넨탈 뷔페 여름 한정 페스타 연다,문어 랍스터 대게 갑오징어 새우 소라 등 해산물 활용 미국식 해물찜 시푸드 보일 준...,https://n.news.naver.com/mnews/article/277/000...,인터엑스 1층 뷔페 레스토랑 브래서리는 오는 6일부터 8월31일까지 쿨 섬머 페스타...
2,2022-07-01 08:51:12,economy,뉴시스,에디슨이노 이승훈 제이스페이스 대표 사내이사 선임,기사내용 요약 우주발사체 사업 본격화 서울 뉴시스 김경택 기자 에디슨이노가 우주발사...,https://n.news.naver.com/mnews/article/003/001...,에디슨이노는 1일 임시주주총회를 통해 사명을 이노시스 로 변경하고 이승훈 제이스페이...
3,2022-07-01 16:11:01,economy,머니투데이,SK바사 해외 사업 조직 개편… 글로벌 탑티어 기업으로 성장 박차,SK바이오사이언스가 글로벌 사업의 고도화를 위해 조직 개편을 단행했다. SK바이오사...,https://n.news.naver.com/mnews/article/008/000...,SK바이오사이언스가 글로벌 사업의 고도화를 위해 기존 해외사업개발실을 백신사업뿐만 ...
4,2022-07-01 21:48:04,economy,경향신문,금융당국 “증시 변동성 완화 조치”,4일부터 석달간 증권사 신용융자담보비율 유지의무 면제 금융당국이 코스피지수가 장중 ...,https://n.news.naver.com/mnews/article/032/000...,1일 1일 금융위원회는 증권 유관기관과 금융시장합동점검회의를 열고 코스피지수가 장중...

## sLLM 답변 데이터 생성
LLM을 이용해서 sLLMㅇ 답변했으면 하는 내용을 생성해낸다. 이 때 답변 품질이 중요하므로, 되도록 상위 모델을 사용하는 것이 좋다.

In [10]:
# 구조화 된 답변 준비
from pydantic import BaseModel, Field
from typing import List 

class StockAnalysis(BaseModel):
    """경제 뉴스 분석 결과 클래스"""

    stock_related: bool = Field(description='뉴스와 주식 종목간의 연관성 여부')
    summary: str = Field(description='뉴스 요약')

    positive_stocks: List[str] = Field(
        default_factory=list,
        description='긍정적 영향이 예상 되는 주식 종목명 목록'
    )

    positive_keywords: List[str] = Field(
        default_factory=list,
        description='긍정적 영향의 근거가 되는 키워드 목록'
    )

    positive_reasons: str = Field(
        description='긍정적 영향이 예상 되는 이유'
    )

    negative_stocks: List[str] = Field(
        default_factory=list,
        description='부정적 영향이 예상 되는 주식 종목명 목록'
    )

    negative_keywords: List[str] = Field(
        default_factory=list,
        description='부정적 영향의 근거가 되는 키워드 목록'
    )

    negative_reasons: str = Field(
        description='부정적 영향이 예상 되는 이유'
    )

In [11]:
from langchain_core.prompts import ChatPromptTemplate

system_prompt = """
당신은 금융/경제 뉴스의 핵심 내용을 요약해 설명하고, 특정 상장 종목에 미치는 긍정/부정 영향 여부,
이유/근거 등을 분석하는 금융 분석 전문가입니다.

다음 출력 지시사항을 지켜주세요.
1. 뉴스와 종목간의 영향성을 발견할 수 없다면:
    - stock_related를 False로 작성하세요.
    - summary에 뉴스의 요약을 작성하세요.
2. 뉴스와 종복간의 영향성을 발견했다면:
    - stock_related를 True로 작성하세요.
    - summary에 뉴스의 요약을 작성하세요.
    - 긍정 영향이 예상되는 종목이 있다면, positive_stocks, positive_keywords, positive_reasons를 작성하세요.
    - 부정 영향이 예상되는 종목이 있다면, negaitive_stocks, negaitive_keywords, negaitive_reasons를 작성하세요.
    - 값이 없는 경우 빈 문자열(''), 빈 리스트([])를 작성하세요.
"""

user_prompt = """
다음 뉴스 기사의 내용에 대해 심층적인 분석을 수행해주세요.

[news]
{news}
"""

prompt = ChatPromptTemplate.from_messages([
    ('system',system_prompt),
    ('human',user_prompt)
])

# 첫 번째 뉴스 기사
news = df['document'][0]
prompt.invoke({'news':news})

ChatPromptValue(messages=[SystemMessage(content="\n당신은 금융/경제 뉴스의 핵심 내용을 요약해 설명하고, 특정 상장 종목에 미치는 긍정/부정 영향 여부,\n이유/근거 등을 분석하는 금융 분석 전문가입니다.\n\n다음 출력 지시사항을 지켜주세요.\n1. 뉴스와 종목간의 영향성을 발견할 수 없다면:\n    - stock_related를 False로 작성하세요.\n    - summary에 뉴스의 요약을 작성하세요.\n2. 뉴스와 종복간의 영향성을 발견했다면:\n    - stock_related를 True로 작성하세요.\n    - summary에 뉴스의 요약을 작성하세요.\n    - 긍정 영향이 예상되는 종목이 있다면, positive_stocks, positive_keywords, positive_reasons를 작성하세요.\n    - 부정 영향이 예상되는 종목이 있다면, negaitive_stocks, negaitive_keywords, negaitive_reasons를 작성하세요.\n    - 값이 없는 경우 빈 문자열(''), 빈 리스트([])를 작성하세요.\n", additional_kwargs={}, response_metadata={}), HumanMessage(content='\n다음 뉴스 기사의 내용에 대해 심층적인 분석을 수행해주세요.\n\n[news]\n앵커 정부가 올해 하반기 우리 경제의 버팀목인 수출 확대를 위해 총력을 기울이기로 했습니다. 특히 수출 중소기업의 물류난 해소를 위해 무역금융 규모를 40조 원 이상 확대하고 물류비 지원과 임시선박 투입 등을 추진하기로 했습니다. 류환홍 기자가 보도합니다. 기자 수출은 최고의 실적을 보였지만 수입액이 급증하면서 올해 상반기 우리나라 무역수지는 역대 최악인 103억 달러 적자를 기록했습니다. 정부가 수출확대에 총력을 기울이기로 한 것은 원자재 가격 상승 등 대외 리스크가 가중되는 상황에서 수출 증가세 지속이야말로 한국경제의 회복을 위한 열쇠라고 본 것입니다. 추경호 경제부총리 겸 기획재정부 장관 정부는 우리 경제의 성장엔진인 수출이 높은 증가세를 지속할 수 있도록 총력을 다하겠습니다. 우선 물류 부담 증가 원자재 가격 상승 등 가중되고 있는 대외 리스크에 대해 적극 대응하겠습니다. 특히 중소기업과 중견기업 수출 지원을 위해 무역금융 규모를 연초 목표보다 40조 원 늘린 301조 원까지 확대하고 물류비 부담을 줄이기 위한 대책도 마련했습니다. 이창양 산업통상자원부 장관 국제 해상운임이 안정될 때까지 월 4척 이상의 임시선박을 지속 투입하는 한편 중소기업 전용 선복 적재 용량 도 현재보다 주당 50TEU 늘려 공급하겠습니다. 하반기에 우리 기업들의 수출 기회를 늘리기 위해 2 500여 개 수출기업을 대상으로 해외 전시회 참가를 지원하는 등 마케팅 지원도 벌이기로 했습니다. 정부는 또 이달 중으로 반도체를 비롯한 첨단 산업 육성 전략을 마련해 수출 증가세를 뒷받침하고 에너지 소비를 줄이기 위한 효율화 방안을 마련해 무역수지 개선에 나서기로 했습니다. YTN 류환홍입니다.\n', additional_kwargs={}, response_metadata={})])

In [16]:
#llm 체인 생성
from langchain.chat_models import init_chat_model

llm = init_chat_model('openai:gpt-4.1', max_retries=5)

chain = prompt | llm.with_structured_output(StockAnalysis)

def analyze_news(news):
    return chain.invoke({'news':news})

analyze_news(news)

StockAnalysis(stock_related=True, summary="2024년 6월 5일부터 개정된 '공유수면 관리 및 매립에 관한 법률'이 시행된다. 앞으로 해상풍력, 해안관광시설 등 바다 및 해안 사용 허가 시 어업인 등 이해관계자의 의견 수렴이 의무화되었으며, 환경 및 수산 자원, 자연경관 보호에도 보다 신경을 써야 한다. 이에 따라 공유수면 점용/사용을 허가받아야 할 사업자들은 이해관계자의 반대, 의견 조율 등 추가 절차를 거치게 되고, 사회적 갈등 방지 및 절차 투명성이 강화될 전망이다.", positive_stocks=[], positive_keywords=[], positive_reasons='', negative_stocks=['씨에스윈드', '유니슨', '한국조선해양', '두산에너빌리티'], negative_keywords=['해상풍력', '공유수면 허가', '환경영향', '어업인 의견', '절차 강화'], negative_reasons='해상풍력 발전시설 등 대규모 공유수면 사용 기업들은 어업인 등 이해관계자 의견 수렴, 공고, 피해 조사 등 절차가 추가되면서 사업 추진이 지연되거나 행정 부담이 증가할 수 있다. 이에 대표적인 해상풍력 및 관련 EPC(설계·조달·시공) 기업인 씨에스윈드, 유니슨, 두산에너빌리티, 한국조선해양 등은 단기적으로 부정적 영향이 예상된다.')

In [13]:
news = df['document'][100]
analyze_news(news)

StockAnalysis(stock_related=True, summary='해양수산부가 5일부터 공유수면 점용·사용 허가 시 어업인 등 이해관계자 의견 수렴을 의무화하는 법 개정 및 시행령을 시행한다. 앞으로 해상풍력 발전, 해변 관광시설 등 대규모 공유수면 개발사업 추진 시 절차가 강화되고, 어업·환경 보호 등 이해관계자 갈등 조정 절차가 포함된다.', positive_stocks=[], positive_keywords=[], positive_reasons='', negative_stocks=['CS윈드', '씨에스베어링', '씨에스윈드', '유니슨', '두산에너빌리티', '삼강엠앤티', '한국조선해양', 'HD현대', '한화오션'], negative_keywords=['해상풍력', '공유수면', '환경영향', '어업인', '허가절차 강화', '이해관계자 의견수렴'], negative_reasons='해상풍력발전, 해변 관광시설 등 공유수면을 장기 점용·개발하는 사업 추진 시 환경 및 어업인 이해관계자 의견 수렴이 의무화되면서, 프로젝트 인허가 절차가 복잡해지고 사업 지연 또는 취소 리스크가 커짐. 이에 따라 해상풍력 관련주 및 해상플랜트·조선/중공업, 시설 건설 관련 종목들에 단기적 부정적 영향이 예상됨.')

In [14]:
import pandas as pd

# 1000건의 데이터 샘플링 -> LLM 질의
df = df[:1000]
df['content'] = df['title'] + '\n' + df['document']

news_df = df['content']
print(len(news_df))
news_df.head()

1000

0    추경호 중기 수출지원 총력 무역금융 40조 확대\n앵커 정부가 올해 하반기 우리 경...
1    해산물·주류 무제한 인터컨티넨탈 뷔페 여름 한정 페스타 연다\n문어 랍스터 대게 갑...
2    에디슨이노 이승훈 제이스페이스 대표 사내이사 선임\n기사내용 요약 우주발사체 사업 ...
3    SK바사 해외 사업 조직 개편… 글로벌 탑티어 기업으로 성장 박차\nSK바이오사이언...
4    금융당국 “증시 변동성 완화 조치”\n4일부터 석달간 증권사 신용융자담보비율 유지의...
Name: content, dtype: str

In [17]:
# 응답 생성 (이 셀만 수정하고 아래 셀들은 그대로 두세요!)
from tqdm import tqdm
import time

# 주피터 환경에서 이 셀을 다시 실행해도 이미 모인 results가 날아가지 않도록 안전장치를 둡니다.
if 'results' not in locals() or len(results) == 0:
    results = []

start_index = len(results)
print(f"현재 {start_index}번 인덱스부터 이어서 분석을 시작합니다.")

# 이미 완료된 개수 이후부터 이어서 루프를 돕니다.
for content in tqdm(news_df[start_index:]):
    result = analyze_news(content)
    results.append(result)
    time.sleep(1)

현재 534번 인덱스부터 이어서 분석을 시작합니다.

100%|██████████| 466/466 [35:42<00:00,  4.60s/it]

In [18]:
# 응답 저장
df['result'] = results
df.head()

,date,category,press,title,document,link,summary,content,result
0,2022-07-03 17:14:37,economy,YTN,추경호 중기 수출지원 총력 무역금융 40조 확대,앵커 정부가 올해 하반기 우리 경제의 버팀목인 수출 확대를 위해 총력을 기울이기로 ...,https://n.news.naver.com/mnews/article/052/000...,"올해 상반기 우리나라 무역수지는 역대 최악인 103억 달러 적자를 기록한 가운데, ...",추경호 중기 수출지원 총력 무역금융 40조 확대\n앵커 정부가 올해 하반기 우리 경...,stock_related=True summary='정부가 중소·중견 수출기업의 수출...
1,2022-07-04 08:07:12,economy,아시아경제,해산물·주류 무제한 인터컨티넨탈 뷔페 여름 한정 페스타 연다,문어 랍스터 대게 갑오징어 새우 소라 등 해산물 활용 미국식 해물찜 시푸드 보일 준...,https://n.news.naver.com/mnews/article/277/000...,인터엑스 1층 뷔페 레스토랑 브래서리는 오는 6일부터 8월31일까지 쿨 섬머 페스타...,해산물·주류 무제한 인터컨티넨탈 뷔페 여름 한정 페스타 연다\n문어 랍스터 대게 갑...,"stock_related=True summary=""인터컨티넨탈 서울 코엑스 브래서리..."
2,2022-07-01 08:51:12,economy,뉴시스,에디슨이노 이승훈 제이스페이스 대표 사내이사 선임,기사내용 요약 우주발사체 사업 본격화 서울 뉴시스 김경택 기자 에디슨이노가 우주발사...,https://n.news.naver.com/mnews/article/003/001...,에디슨이노는 1일 임시주주총회를 통해 사명을 이노시스 로 변경하고 이승훈 제이스페이...,에디슨이노 이승훈 제이스페이스 대표 사내이사 선임\n기사내용 요약 우주발사체 사업 ...,stock_related=True summary='에디슨이노(이노시스)가 사명을 변...
3,2022-07-01 16:11:01,economy,머니투데이,SK바사 해외 사업 조직 개편… 글로벌 탑티어 기업으로 성장 박차,SK바이오사이언스가 글로벌 사업의 고도화를 위해 조직 개편을 단행했다. SK바이오사...,https://n.news.naver.com/mnews/article/008/000...,SK바이오사이언스가 글로벌 사업의 고도화를 위해 기존 해외사업개발실을 백신사업뿐만 ...,SK바사 해외 사업 조직 개편… 글로벌 탑티어 기업으로 성장 박차\nSK바이오사이언...,stock_related=True summary='SK바이오사이언스가 글로벌 사업 ...
4,2022-07-01 21:48:04,economy,경향신문,금융당국 “증시 변동성 완화 조치”,4일부터 석달간 증권사 신용융자담보비율 유지의무 면제 금융당국이 코스피지수가 장중 ...,https://n.news.naver.com/mnews/article/032/000...,1일 1일 금융위원회는 증권 유관기관과 금융시장합동점검회의를 열고 코스피지수가 장중...,금융당국 “증시 변동성 완화 조치”\n4일부터 석달간 증권사 신용융자담보비율 유지의...,stock_related=True summary='금융당국이 최근 증시 급락 및 변...

In [19]:
# json 변환
import json
# - pydantic.BaseModel.model_dump() -> dict
# - pydantic.BaseModel.model_dump_json() -> json_str

# json 파싱
def parse_to_json(obj):
    return obj.model_dump_json()

df['result_json'] = df['result'].apply(parse_to_json)

In [20]:
# 결측치 제거
df = df.dropna(subset=['result_json'])
df = df.reset_index(drop=True)
df.head()

,date,category,press,title,document,link,summary,content,result,result_json
0,2022-07-03 17:14:37,economy,YTN,추경호 중기 수출지원 총력 무역금융 40조 확대,앵커 정부가 올해 하반기 우리 경제의 버팀목인 수출 확대를 위해 총력을 기울이기로 ...,https://n.news.naver.com/mnews/article/052/000...,"올해 상반기 우리나라 무역수지는 역대 최악인 103억 달러 적자를 기록한 가운데, ...",추경호 중기 수출지원 총력 무역금융 40조 확대\n앵커 정부가 올해 하반기 우리 경...,stock_related=True summary='정부가 중소·중견 수출기업의 수출...,"{""stock_related"":true,""summary"":""정부가 중소·중견 수출기..."
1,2022-07-04 08:07:12,economy,아시아경제,해산물·주류 무제한 인터컨티넨탈 뷔페 여름 한정 페스타 연다,문어 랍스터 대게 갑오징어 새우 소라 등 해산물 활용 미국식 해물찜 시푸드 보일 준...,https://n.news.naver.com/mnews/article/277/000...,인터엑스 1층 뷔페 레스토랑 브래서리는 오는 6일부터 8월31일까지 쿨 섬머 페스타...,해산물·주류 무제한 인터컨티넨탈 뷔페 여름 한정 페스타 연다\n문어 랍스터 대게 갑...,"stock_related=True summary=""인터컨티넨탈 서울 코엑스 브래서리...","{""stock_related"":true,""summary"":""인터컨티넨탈 서울 코엑스..."
2,2022-07-01 08:51:12,economy,뉴시스,에디슨이노 이승훈 제이스페이스 대표 사내이사 선임,기사내용 요약 우주발사체 사업 본격화 서울 뉴시스 김경택 기자 에디슨이노가 우주발사...,https://n.news.naver.com/mnews/article/003/001...,에디슨이노는 1일 임시주주총회를 통해 사명을 이노시스 로 변경하고 이승훈 제이스페이...,에디슨이노 이승훈 제이스페이스 대표 사내이사 선임\n기사내용 요약 우주발사체 사업 ...,stock_related=True summary='에디슨이노(이노시스)가 사명을 변...,"{""stock_related"":true,""summary"":""에디슨이노(이노시스)가 ..."
3,2022-07-01 16:11:01,economy,머니투데이,SK바사 해외 사업 조직 개편… 글로벌 탑티어 기업으로 성장 박차,SK바이오사이언스가 글로벌 사업의 고도화를 위해 조직 개편을 단행했다. SK바이오사...,https://n.news.naver.com/mnews/article/008/000...,SK바이오사이언스가 글로벌 사업의 고도화를 위해 기존 해외사업개발실을 백신사업뿐만 ...,SK바사 해외 사업 조직 개편… 글로벌 탑티어 기업으로 성장 박차\nSK바이오사이언...,stock_related=True summary='SK바이오사이언스가 글로벌 사업 ...,"{""stock_related"":true,""summary"":""SK바이오사이언스가 글로..."
4,2022-07-01 21:48:04,economy,경향신문,금융당국 “증시 변동성 완화 조치”,4일부터 석달간 증권사 신용융자담보비율 유지의무 면제 금융당국이 코스피지수가 장중 ...,https://n.news.naver.com/mnews/article/032/000...,1일 1일 금융위원회는 증권 유관기관과 금융시장합동점검회의를 열고 코스피지수가 장중...,금융당국 “증시 변동성 완화 조치”\n4일부터 석달간 증권사 신용융자담보비율 유지의...,stock_related=True summary='금융당국이 최근 증시 급락 및 변...,"{""stock_related"":true,""summary"":""금융당국이 최근 증시 급..."

## 학습용 데이터 셋 변환
- system
- user(human)
- assistant

In [21]:
df['system'] = system_prompt

df = df.rename(columns={
    'content':'user',
    'result_json':'assistant'
})

df[['system','user','assistant']]

,system,user,assistant
0,"\n당신은 금융/경제 뉴스의 핵심 내용을 요약해 설명하고, 특정 상장 종목에 미치는...",추경호 중기 수출지원 총력 무역금융 40조 확대\n앵커 정부가 올해 하반기 우리 경...,"{""stock_related"":true,""summary"":""정부가 중소·중견 수출기..."
1,"\n당신은 금융/경제 뉴스의 핵심 내용을 요약해 설명하고, 특정 상장 종목에 미치는...",해산물·주류 무제한 인터컨티넨탈 뷔페 여름 한정 페스타 연다\n문어 랍스터 대게 갑...,"{""stock_related"":true,""summary"":""인터컨티넨탈 서울 코엑스..."
2,"\n당신은 금융/경제 뉴스의 핵심 내용을 요약해 설명하고, 특정 상장 종목에 미치는...",에디슨이노 이승훈 제이스페이스 대표 사내이사 선임\n기사내용 요약 우주발사체 사업 ...,"{""stock_related"":true,""summary"":""에디슨이노(이노시스)가 ..."
3,"\n당신은 금융/경제 뉴스의 핵심 내용을 요약해 설명하고, 특정 상장 종목에 미치는...",SK바사 해외 사업 조직 개편… 글로벌 탑티어 기업으로 성장 박차\nSK바이오사이언...,"{""stock_related"":true,""summary"":""SK바이오사이언스가 글로..."
4,"\n당신은 금융/경제 뉴스의 핵심 내용을 요약해 설명하고, 특정 상장 종목에 미치는...",금융당국 “증시 변동성 완화 조치”\n4일부터 석달간 증권사 신용융자담보비율 유지의...,"{""stock_related"":true,""summary"":""금융당국이 최근 증시 급..."
...,...,...,...
995,"\n당신은 금융/경제 뉴스의 핵심 내용을 요약해 설명하고, 특정 상장 종목에 미치는...",1년 넘게 입출금 없는 은행 예금 15조 8천억 원…“전면 재점검해 사고 예방해야”...,"{""stock_related"":true,""summary"":""국내 4대 은행(KB국민..."
996,"\n당신은 금융/경제 뉴스의 핵심 내용을 요약해 설명하고, 특정 상장 종목에 미치는...",SGA 한국교육학술정보원과 204억원 규모 나이스 구축 공급계약 체결\nSGA는 한...,"{""stock_related"":true,""summary"":""SGA는 한국교육학술정보..."
997,"\n당신은 금융/경제 뉴스의 핵심 내용을 요약해 설명하고, 특정 상장 종목에 미치는...",“갯벌의 숨은 매력 사진에 담아주세요”\n해수부·해양환경공단 한국의 갯벌 가치 알린...,"{""stock_related"":false,""summary"":""해양수산부와 해양환경공..."
998,"\n당신은 금융/경제 뉴스의 핵심 내용을 요약해 설명하고, 특정 상장 종목에 미치는...",더뉴스 월세 60% 시대·매수 심리 뚝...부동산 시장 변화는\n진행 김영수 앵커 ...,"{""stock_related"":true,""summary"":""최근 부동산 시장은 월세..."
999,"\n당신은 금융/경제 뉴스의 핵심 내용을 요약해 설명하고, 특정 상장 종목에 미치는...",삼성전자 상반기 성과급 쏜다…반도체·스마트폰 ‘100%’\n호실적에 기본급 최대 1...,"{""stock_related"":true,""summary"":""삼성전자가 2024년 상..."

In [22]:
# json 파일 출력
df[['system','user','assistant']].to_json(
    'train.json',           # 파일명
    orient='records',       # dataframe 각 행이 하나의 json 객체로 저장
    force_ascii=False,      # 비영어권문자 ascii 변환 안함
    indent=4                # 들여쓰기
)

In [23]:
# hugging face dataset upload
from datasets import Dataset
import os

dataset = Dataset.from_pandas(df[['system','user','assistant']])
dataset.push_to_hub(
    'sim2084/naver-economy-news2stock',
    token = os.environ['HF_TOKEN']
)

Setting num_proc from 1 back to 1 for the train split to disable multiprocessing as it only contains one shard.

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0): |          |  0.00B /  0.00B

New Data Upload: |          |  0.00B /  0.00B

CommitInfo(commit_url='https://huggingface.co/datasets/sim2084/naver-economy-news2stock/commit/f5783ad933d1764e6bc309fcbf095c539b9af6b0', commit_message='Upload dataset', commit_description='', oid='f5783ad933d1764e6bc309fcbf095c539b9af6b0', pr_url=None, repo_url=RepoUrl('https://huggingface.co/datasets/sim2084/naver-economy-news2stock', endpoint='https://huggingface.co', repo_type='dataset', repo_id='sim2084/naver-economy-news2stock'), pr_revision=None, pr_num=None)